// Copyright (c) 2021, wtt_module and contributors
// For license information, please see license.txt

frappe.ui.form.on('Appointment Order', {
	refresh:function(frm,cdt,cdn){
		frm.add_custom_button('Get Format', () => {
			frappe.call({
			method: 'wtt_module.wtt_module.doctype.appointment_order.appointment_order.get_status',
			args: { cur: frm.doc.annual_salary},
			callback(r) {
				frm.set_value('in_words',r.message)
				if(frm.doc.order_type=="Fresher")
	{
	var htvalue='Dear <b>Mr. '+frm.doc.employee_name+'</b><br><br>'
	htvalue+='We are pleased to offer you an appointment as <b>'+frm.doc.designation+'</b> with effect from <b>'+frm.doc.date+'</b>.You will be posted at Head Office Tirupur. You need to be stationed in the place of respective Head office and discharge your duties, on the following terms and conditions:'
	htvalue+='<br><br><b><u>Remuneration:</u></b><br><br>You will be paid a salary of <b>Rs. '+frm.doc.annual_salary+' /- per Annum (CTC) ('+frm.doc.in_words+')</b>. Salary structure enclosed (Annexure-I), you will not be entitled to any other allowances whatsoever.'
	htvalue+='<br><br><b><u>Training Period:</u></b><br><br>You will be in training for a period of Six months and probation for a period of Six months with effect from your date of Joining. After the Successful completion of your training period, you will be entitled for all benefits as per the policy. The Training & Probation period may be extended if the performance of the TRAINEE is found poor or Not Satisfactory.'
	htvalue+='<br><br><b><u>Transferability:</u></b><br><br>You are liable to be transferred / deputed to any other section / department or site of the company, or to any of the group / sister companies, that may be existing or acquired in future anywhere in territory of India at management’s sole discretion.'
	htvalue+='<br><br><b><u>Restrictions on outside business activities:</u></b><br><br>During your Training, You shall devote your full time, energy and ability exclusively to the causes of business interest of WTT Technology Services India Pvt Ltd and shall not Without our prior written consent, render to other service of any kind free or for compensation, or engage in any other business activity that would materially interfere with the performance of your obligation under this agreement.  You have to further represent that, you have no other outstanding commitments inconsistent with any of the terms of this Agreement.'
	htvalue+='<br><br><b><u>Covenant not to compete:</u></b><br><br>During your period of Association and 12 months after expiry of the period, you shall not, directly or indirectly, whether as partner, employee, creditor, shareholders or otherwise, promote, participate or engage in any activity or other business competitive/inimical to business interest of WTT Technology Services India Pvt Ltd.'
	htvalue+='<br><br><b><u>Non-disclosure obligations:</u></b><br><br>At all times during and after your association, You will hold in strictest confidence and not use for your own purpose or the purposes of others or disclose any thing even resembling on the Intellectual Properties belonging to WTT Technology Services India Pvt Ltd. to any person,  firm or corporation.  You will not publish or submit for publication any technical or other articles pertaining in any way to WTT Technology Services India Pvt Ltd. Intellectual Properties without our authorization in writing.'
	htvalue+='<br><br><b><u>Intellectual property:</u></b><br><br>The term Intellectual Property as it is used in this Agreement, shall include but not be limited to the following;<br><br>&emsp;a)	Business or financial records, strategies, forecasts, budgets, Projections License, prices, costs, lists of current and prospective customers. Vendors Resume of Applicants of all category, training materials etc.<br><br>&emsp;b)	Manufacturing techniques plans, processes formulas developments, experiments work-in-process, trade secrets ideas processes formulas training materials source codes, data, programs, inventions, confidential information, data, designs, drawings, consents, including but not limited to agnatic storage media compute memories or any electronic storage media which relates to the actual or prospective products, sales or businesses of WTT Technology Services India Pvt Ltd and which is not readily available to the public.  That know-how or any other information (Collective “inventions”) in whatever form, that term shall also include any information belonging to third parties in WTT Technology Services India Pvt Ltd’s possession and any information conceived, originated, discovered or developed by yourself in the course of your association with the company.'
	htvalue+='<br><br><b><u>Idle period:</u></b><br><br>You have to agree that you shall not claim any remuneration for the days your services were not availed by WTT Technology Services India Pvt Ltd.'
	htvalue+='<br><br><b><u>Termination on normal grounds:</u></b><br><br>WTT Technology Services India Pvt. Ltd. reserves the right to terminate the association/service on the normal grounds other than that of the in disciplinary actions with a prior notice of 3 months remuneration in lieu of notice.'
	htvalue+='<br><br><b><u>Return of WTT INDIA’s property:</u></b><br><br>You agree and undertake to return to WTT Technology Services India Pvt. Ltd all our files, drawings, blueprint, notebooks, memoranda, correspondence specifications, devices,  documents training materials & manuals, list of clients, diskettes and any material that embodies our Intellectual Properties of Confidential Information.  You further undertake that you shall not recreate any of the foregone.  You further agree that only a relieving order signed by the Authorized Signatory of WTT Technology Services India Pvt. Ltd. will confirm that you have surrendered all our material in your possession.'
	htvalue+='<br><br><b><u>Communication Address:</u></b><br><br>Your address indicated above shall be deemed to be correct address for sending you any communication and unless changed by the written intimation, the communication sent to you at the above address shall be deemed to have been correctly served.'
	htvalue+='<br><br><b><u>Rules and Regulations:</u></b><br><br>In all other matters not specifically mentioned herein, you will abide by the service/Standing Orders as applicable, enforced, amended or altered from time to time during the course of your employment.'
	htvalue+='<br><br><b><u>Complementary:</u></b><br><br>You shall not accept any presents, commissions, or any kind of gratification in Cash or kind from any person, party, firm or company having dealings with WTT Technology Services India Pvt Ltd and if you are offered you will report the same immediately to WTT Technology Services India Pvt. Ltd.'
	htvalue+='<br><br><b><u>Termination:</u></b><br><br>This appointment is liable for termination at any time by giving 90 Working Days on either side in writing.This appointment order constitutes a valid and binding contract of service for the company and yourself.If the above terms and conditions are acceptable, you are requested to sign and deliver the duplicate copy of this order as a token of your acceptance.'
	htvalue+='<br><br><b><u>Service Agreement:</u></b><br><br>Articles of agreement made at Tirupur this ________________ between M/s WTT Technology Services India Private Limited, having its office at No3 College Cross Road, Avarankadu, Tirupur – 641602 ( Hearin after to as WTT technology Services India Private Limited and their Successor ) and <br>_________________________________________________________________________<br>_________________________________________________________________________<br>_________________________________________________________________________<br>_________________________________________________________________________<br>( Herein after referred as ASSOCIATOR ) which expressions shall be deemed to include his legal heirs, successors, executors and administrators,WHEREAS WTT Technology Services India Private Limited having its operation and maintenance of water treatment and their training methods and management technics and their intellectual properties; WHEREAS the ASSOSIATOR desiers to join them and to serve with their business and WTT Technology Service India Private Limited agrees to engage him/her as part their investment.'
	htvalue+='WHEREAS the ASSOCIATOR agrees that his/her association with the name WTT Technology Services India Private Limited and exposure to their exclusive intellectual properties will cause immense enrichment of his professional standing and consequently enhancement of his earning capacity. Hence, agrees that this agreement is of commercial value to him as well as to WTT Technology Services India Private Limited so he commits and undertakes to serve their business interest by the way of technical contributions or otherwise for a specified period to enable them to recover their investment on him/her or compensate them by way of penalty in the event of non-fulfillment of his obligations under this agreement.The ASSOCIATOR shall be with WTT Technology Services India Private Limited Group firms and companies for a period of ____________ from the date of this agreement to the effect that he will develop his technical skills initially and consequently enrich his knowledge towards the productivity enhancement over a period of time.'
	htvalue+='<br><br><br>With best regards<br><br><b>SIVAKUMAR.P<br>General Manager - Admin<br>WTT Technology Services India Pvt Ltd</b><br><br>'
	htvalue+='<br>I accept the above Offer and shall join duties on _____________<br><br>'
	htvalue+='I accept all the terms and conditions and shall abide by the service rules of the Company.<br><br>'
	htvalue+='I hereby declare that I am accepting to work with the assigned designation willfully and later on, I will not claim for departmental change whatsoever based on my qualification.'
	htvalue+='<br><br><br><br>Signature ______________<br>Dated ______________'
	frm.set_value('html_text',htvalue);
	}
	else if(frm.doc.order_type=="Agreement")
	{
	var htvalue='Dear <b>Mr. '+frm.doc.employee_name+'</b><br><br>'
	htvalue+='We are pleased to offer you an appointment as <b>'+frm.doc.designation+'</b> effect from <b>'+frm.doc.date+'</b>.You will be posted at Head Office Tirupur. You need to be stationed in the place of respective Head office and discharge your duties, on the following terms and conditions:'
	htvalue+='<br><br><b><u>Remuneration:</u></b><br><br>You will be paid a stipend of <b>Rs.12000 per month</b> till the completion of your training period.'
	htvalue+='<br><br><b><u>Training Period:</u></b><br><br>You will be in training for a period of One year with effect from your date of Joining. After the Successful completion of your training period, you will be entitled for all Statutory and Non-Statutory benefits as per the policy. The Training period may be extended if the performance of the TRAINEE is found poor or Not Satisfactory.'
	htvalue+='<br><br><b><u>Transferability:</u></b><br><br>You are liable to be transferred / deputed to any other section / department or site of the company, or to any of the group / sister companies, that may be existing or acquired in future anywhere in territory of India at management’s sole discretion.'
	htvalue+='<br><br><b><u>Restrictions on outside business activities:</u></b><br><br>During your Training, You shall devote your full time, energy and ability exclusively to the causes of business interest of WTT Technology Services India Pvt Ltd and shall not Without our prior written consent, render to other service of any kind free or for compensation, or engage in any other business activity that would materially interfere with the performance of your obligation under this agreement.  You have to further represent that, you have no other outstanding commitments inconsistent with any of the terms of this Agreement.'
	htvalue+='<br><br><b><u>Service Agreement:</u></b><br><br>Articles of agreement made at Tirupur this ________________ between M/s WTT Technology Services India Private Limited, having its office at No3 College Cross Road, Avarankadu, Tirupur – 641602 ( Hearin after to as WTT technology Services India Private Limited and their Successor ) and _________________________________________________________________________<br>_________________________________________________________________________<br>_________________________________________________________________________<br>( Herein after referred as ASSOCIATOR ) which expressions shall be deemed to include his legal heirs, successors, executors and administrators,'
	htvalue+='<br><br>WHEREAS WTT Technology Services India Private Limited having its operation and maintenance of water treatment and their training methods and management technics and their intellectual properties; WHEREAS the ASSOSIATOR desiers to join them and to serve with their business and WTT Technology Service India Private Limited agrees to engage him/her as part their investment.'
	htvalue+='<br><br>WHEREAS the ASSOCIATOR agrees that his/her association with the name WTT Technology Services India Private Limited and exposure to their exclusive intellectual properties will cause immense enrichment of his professional standing and consequently enhancement of his earning capacity. Hence, agrees that this agreement is of commercial value to him as well as to WTT Technology Services India Private Limited so he commits and undertakes to serve their business interest by the way of technical contributions or otherwise for a specified period to enable them to recover their investment on him/her or compensate them by way of penalty in the event of non-fulfillment of his obligations under this agreement.'
	htvalue+='<br><br><b><u>IT IS HEREBY AGREED AS UNDER:</u></b><br><br><b><u>1. PERIOD</u></b><br><br>The ASSOCIATOR shall be with WTT Technology Services India Private Limited Group firms and companies for a period of ____________ from the date of this agreement to the effect that he will develop his technical skills initially and consequently enrich his knowledge towards the productivity enhancement over a period of time.'
	htvalue+='<br><br><b><u>2. REMUNERATION</u></b><br><br>The ASSOCIATOR shall be paid a monthly remuneration in cash or kind. Which shall be revised from time to time commensurate with his competence and his contribution to WTT Technology Services India Private Limited’s business.'
	htvalue+='<br><br><b><u>3. TRANSFERABILITY</u></b><br><br>WTT Technology Services India Private Limited is freely entitled to transfer and post the ASSOCIATOR to any of their branches in India and also to transfer the rights conferred to them by this agreement as part of their business deals and the ASSOCIATORS undertakes to serve such transferees.'
	htvalue+='<br><br><b><u>4. RESTRICTIONS ON OUTSIDE BUSINESS ACTIVITIES</u></b><br><br>During his Training, Associations the ASSOCIATOR shall devote his full time, energy and ability exclusively to the causes of business interest of WTT Technology Services India Private Limited and shall not without their prior written consent, render to other service of any kind free or for compensation, or engage in any other business activity that would materially interfere with the performance of his obligation under this agreement.  The ASSOCIATOR further represents that he has no other outstanding commitments inconsistent with any of the terms of this Agreement.'
	htvalue+='<br><br><b><u>5. COVENANT NOT TO COMPETE</u></b><br><br>During his period of Association and 12 months after expiry of the period of this agreement the ASSOCIATOR shall not, directly or indirectly,  whether as partner,  employee, creditor,  shareholders or otherwise,  promote,  participate or engage in any activity or other business competitive/inimical to business interest of  WTT Technology Services India Private Limited.'
	htvalue+='<br><br><b><u>6. NON-DISCLOSURE OBLIGATIONS</u></b><br><br>At all times during and after his association, the ASSOCIATOR will hold in strictest confidence and not use for his own purpose or the purposes of others or disclose any thing even resembling on the Intellectual Properties belonging to WTT Technology Services India Private Limited to any person,  firm or corporation.  He will not publish or submit for publication any technical or other articles pertaining in any way to WTT Technology Services India Private Limited’s Intellectual Properties without their authorization in writing.'
	htvalue+='<br><br><b><u>7.  INTELLECTUAL PROPERTY</u></b><br><br>The term Intellectual Property as it is used in this Agreement, shall include but not be limited to the following;  Business or financial records, strategies, forecasts, budgets, Projections license, prices, costs, lists of current and prospective customers.Vendors  Resume of Applicants of all category, training materials etc.Manufacturing techniques plans, processes formulas developments, experiments work-in-process,  trade secrets ideas processes formulas training materials source codes, data,  programs, inventions, confidential information, data, designs, drawings, consents, including but not limited to agnatic storage media compute memories or any electronic storage media which relates to the actual or prospective products, sales or businesses of WTT Technology Services India Private Limited and which is not readily available to the public.  That know-how or any other information (Collective “inventions”) in whatever form, that term shall also include any information belonging to third parties in WTT Technology Services India Private Limited’s possession and any information conceived, originated, discovered or developed by the ASSOCIATOR in the course of his association with WTT Technology Services India Private Limited.'
	htvalue+='<br><br><b><u>8. IDLE PERIOD</u></b><br><br>The ASSOCIATOR agrees that he shall not claim any remuneration for the days his services were not availed by WTT Technology Services India Private Limited due to this lapses or otherwise.  However, if they allow and agreed by him within 30 days.  The period as in clause (1) shall also be automatically extended to the extend of these days.'
	htvalue+='<br><br><b><u>9. DISCIPLINARY ACTIONS</u></b><br><br>WTT Technology Services India Private Limited reserve the right to terminate the associate/service of the ASSOCIATOR as disciplinary action on the grounds including and not limited to Non-co-operation and Loss of interest in assignment, Absenteeism,  Irregularity,  Non-punctuality to work place, Engaging in Criminal Activities, Non-adherence to the terms of his agreement,  etc.'
	htvalue+='<br><br><b><u>10. TERMINATION ON NORMAL GROUNDS</u></b><br><br>WTT Technology Services India Private Limited reserves the right to terminate the association/service for the ASSOCIATOR on the normal grounds other than that mentioned in Clause (9) with a prior notice of 15 days or remuneration in lieu of notice.'
	htvalue+='<br><br><b><u>11. RETURN OF WTT Technology Services India Private Limited’s PROPERTY</u></b><br><br>The ASSOCIATOR agrees and undertakes to return to WTT Technology Services India Private Limited all their files drawings, blueprint, notebooks, memoranda,  correspondences specifications,  devices,  documents training materials & manuals, list of clients, diskettes and any material that embodies their Intellectual Properties of Confidential Information.  He further undertakes that he shall not recreate any of the foregone.  He further agrees that only a relieving order signed by the Authorized Signatory of  WTT Technology Services India Private Limited  will confirm that he has surrendered all their material in his possession.'
	htvalue+='<br><br><b><u>12. PENALITY</u></b><br><br>In the event of violation of clause (1) by the ASSOCIATOR or his termination by WTT Technology Services India Private Limited under clause (9) he shall pay them a penalty of sum of rupees as per the last drawn Gross salary equivalent to the number of years yet to service for completing the agreement period, together with compound interest @18% per annum from the date on which demand for penalty is made upon him/her. In the event of violation of clause 5 and 6 the ASSOCIATOR agree and undertakes to pay the penalties as decided by WTT Technology Services India Private Limited. If the termination is on mutual consent between WTT Technology services and ASSOCIATOR penalty may be reduced or disclaimed according to the nature of termination. This will not be applicable when the termination is as per clause (10)'
	htvalue+='<br><br><b><u>13. ARBITRATION</u></b><br><br>In the event of any dispute of claim or liability in relation to or arising out of or in connection with this agreement, the same shall be referred to the Sole Arbitrator appointed by WTT Technology Services India Private Limited.  The reference adjudication and award of arbitration proceedings shall be in accordance with   “Arbitration and Conciliation Act 1996“ or of any other codification or re-enactment thereof. The Arbitration proceedings shall be held in Tirupur/Coimbatore courts of Tamilnadu state and no other courts have jurisdiction over any such dispute.'
	htvalue+='<br><br><b><u>14. INJUNCTIVE RELIEF</u></b><br><br>In the event of a breach of his obligations under the Non-Discloser obligation or any of their Intellectual Property Rights,   WTT Technology Services India Private Limited will be entitled to seek, in addition to any other remedies available, immediate injunctive relief without bond to prevent the breach or threatened breach of any obligation hereunder, and such remedies will be cumulative and not exclusive.'
	htvalue+='<br><br><b><u>15. INTEGRATION</u></b><br><br>This agreement contains the entire agreement between WTT Technology Services India Private Limited and ASSOCIATOR and supersedes all prior oral and written agreements,  understandings,  commitments and practices between them,  including all prior agreements,  whether or not fully performed by the  ASSOCIATOR  before the date of this agreement.  No oral modifications express or implied may be made except by a writing signed by both parties.  No one other than the ASSOCIATOR (or) WTT Technology Services India Private Limited authorized to alter to vary the terms of this agreement.  Any representation contrary to this agreement, express or implied written of total hereby disclaimed.'
	htvalue+='<br><br><b><u>16. ADDRESSES FOR THE PURPOSE OF COMMUNICATION</u></b><br><br>All mails/communications from  WTT Technology Services India Private Limited to  ASSOCIATOR and from arbitrator to ASSOCIATOR  shall deem to have been delivered,  if posted to the ASSOCIATOR’s address as given in this Agreement  “  Under Certificate of Posting “ as also by E-mail.  The ASSOCIATOR hereby that it is his responsibility and undertake to make his own arrangements to receive such mails at his new address,  in case of his shifting.'
	htvalue+='<br><br><b><u>17. SEVERABILITY</u></b><br><br>If any provision of this agreement is invalid or unenforceable, the reminder of this agreement shall nevertheless remain in full force and effect.  If any provision is held invalid or unenforceable with respect to particular circumstances, it shall nevertheless remain in full force and affect in all other circumstances.'
	htvalue+='<br><br><b><u>Termination:</u></b><br><br>This appointment is liable for termination at any time by giving three months notice on either side in writing.'
	htvalue+='<br><br>This appointment order constitutes a valid and binding contract of service for the company and yourself.<br><br>'
	htvalue+='If the above terms and conditions are acceptable, you are requested to sign and deliver the duplicate copy of this order as a token of your acceptance.'
	htvalue+='<br><br><br>With best regards<br><br><b>SIVAKUMAR.P<br>General Manager - Admin<br>WTT Technology Services India Pvt Ltd</b><br><br>'
	htvalue+='<br><br>I accept the above Offer and shall join duties on _____________'
	htvalue+='<br><br>I accept all the terms and conditions and shall abide by the service rules of the Company.'
	htvalue+='<br><br>I hereby declare that I am accepting to work with the assigned designation willfully and later on, I will not claim for departmental change whatsoever based on my qualification.'
	htvalue+='<br><br>I further declare that during the agreement period of _______________ signed by me, I will not request the company to relieve me from the services due to any reason.'
	htvalue+='<br><br><br><br>Signature ______________<br>Dated ______________'

	frm.set_value('html_text',htvalue);
	}
	else if(frm.doc.order_type=="Experience"){
		var htvalue='Dear <b>Mr. '+frm.doc.employee_name+'</b><br><br>'
		htvalue+='We are pleased to offer you an appointment as <b>'+frm.doc.designation+'</b> with effect from <b>'+frm.doc.date+'</b>.You will be posted at Head Office Tirupur. You need to be stationed in the place of respective Head office and discharge your duties, on the following terms and conditions:'
		htvalue+='<br><br><b><u>Remuneration:</u></b><br><br>You will be paid a salary of <b>Rs. '+frm.doc.annual_salary+' /- per Annum (CTC) ('+frm.doc.in_words+')</b>. Salary structure enclosed (Annexure-I), you will not be entitled to any other allowances whatsoever.'
		htvalue+='<br><br><b><u>Probation:</u></b><br><br>You will be on probation for a period of One year from the date of Joining. The period may be extended at the sole discretion of the management.'
		htvalue+='<br><br><b><u>Transferability:</u></b><br><br>You are liable to be transferred / deputed to any other section / department or site of the company, or to any of the group / sister companies, that may be existing or acquired in future anywhere in territory of India at management’s sole discretion.'
		htvalue+='<br><br><b><u>Restrictions on outside business activities:</u></b><br><br>During your Training, You shall devote your full time, energy and ability exclusively to the causes of business interest of WTT Technology Services India Pvt Ltd and shall not Without our prior written consent, render to other service of any kind free or for compensation, or engage in any other business activity that would materially interfere with the performance of your obligation under this agreement.  You have to further represent that, you have no other outstanding commitments inconsistent with any of the terms of this Agreement.'
		htvalue+='<br><br><b><u>Covenant not to compete:</u></b><br><br>During your period of Association and 12 months after expiry of the period, you shall not, directly or indirectly, whether as partner, employee, creditor, shareholders or otherwise, promote, participate or engage in any activity or other business competitive/inimical to business interest of WTT Technology Services India Pvt Ltd.'
		htvalue+='<br><br><b><u>Non-disclosure obligations:</u></b><br><br>At all times during and after your association, You will hold in strictest confidence and not use for your own purpose or the purposes of others or disclose any thing even resembling on the Intellectual Properties belonging to WTT Technology Services India Pvt Ltd. to any person,  firm or corporation.  You will not publish or submit for publication any technical or other articles pertaining in any way to WTT Technology Services India Pvt Ltd. Intellectual Properties without our authorization in writing.'
		htvalue+='<br><br><b><u>Intellectual property:</u></b><br><br>The term Intellectual Property as it is used in this Agreement, shall include but not be limited to the following;<br>'
		htvalue+='a) Business or financial records, strategies, forecasts, budgets, Projections License, prices, costs, lists of current and prospective customers. Vendors Resume of Applicants of all category, training materials etc.<br>'
		htvalue+='b) Manufacturing techniques plans, processes formulas developments, experiments work-in-process, trade secrets ideas processes formulas training materials source codes, data, programs, inventions, confidential information, data, designs, drawings, consents, including but not limited to agnatic storage media compute memories or any electronic storage media which relates to the actual or prospective products, sales or businesses of WTT Technology Services India Pvt Ltd and which is not readily available to the public.  That know-how or any other information (Collective “inventions”) in whatever form, that term shall also include any information belonging to third parties in WTT Technology Services India Pvt Ltd’s possession and any information conceived, originated, discovered or developed by yourself in the course of your association with the company.'
		htvalue+='<br><br><b><u>Idle period:</u></b><br><br>You have to agree that you shall not claim any remuneration for the days your services were not availed by WTT Technology Services India Pvt Ltd.'
		htvalue+='<br><br><b><u>Termination on normal grounds:</u></b><br><br>WTT Technology Services India Pvt. Ltd. reserves the right to terminate the association/service on the normal grounds other than that of the in disciplinary actions with a prior notice of 3 months remuneration in lieu of notice.'
		htvalue+='<br><br><b><u>Return of WTT INDIA’s property:</u></b><br><br>You agree and undertake to return to WTT Technology Services India Pvt. Ltd all our files, drawings, blueprint, notebooks, memoranda, correspondence specifications, devices,  documents training materials & manuals, list of clients, diskettes and any material that embodies our Intellectual Properties of Confidential Information.  You further undertake that you shall not recreate any of the foregone.  You further agree that only a relieving order signed by the Authorized Signatory of WTT Technology Services India Pvt. Ltd. will confirm that you have surrendered all our material in your possession.'
		htvalue+='<br><br><b><u>Communication Address:</u></b><br><br>Your address indicated above shall be deemed to be correct address for sending you any communication and unless changed by the written intimation, the communication sent to you at the above address shall be deemed to have been correctly served.'
		htvalue+='<br><br><b><u>Rules and Regulations:</u></b><br><br>In all other matters not specifically mentioned herein, you will abide by the service/Standing Orders as applicable, enforced, amended or altered from time to time during the course of your employment.'
		htvalue+='<br><br><b><u>Complementary:</u></b><br><br>You shall not accept any presents, commissions, or any kind of gratification in Cash or kind from any person, party, firm or company having dealings with WTT Technology Services India Pvt Ltd and if you are offered you will report the same immediately to WTT Technology Services India Pvt. Ltd.'
		htvalue+='<br><br><b><u>Termination:</u></b><br><br>This appointment is liable for termination at any time by giving 90 Working Days on either side in writing.<br><br>'
		htvalue+='This appointment order constitutes a valid and binding contract of service for the company and yourself.<br><br>'
		htvalue+='If the above terms and conditions are acceptable, you are requested to sign and deliver the duplicate copy of this order as a token of your acceptance.'
		htvalue+='<br><br><b><u>Service Agreement:</u></b><br><br>Articles of agreement made at Tirupur this ________________ between M/s WTT Technology Services India Private Limited, having its office at No3 College Cross Road, Avarankadu, Tirupur – 641602 ( Hearin after to as WTT technology Services India Private Limited and their Successor ) and _________________________________________________________________________<br>_________________________________________________________________________<br>_________________________________________________________________________<br>_________________________________________________________________________<br>( Herein after referred as ASSOCIATOR ) which expressions shall be deemed to include his legal heirs, successors, executors and administrators,'
		htvalue+='<br><br>WHEREAS WTT Technology Services India Private Limited having its operation and maintenance of water treatment and their training methods and management technics and their intellectual properties; WHEREAS the ASSOSIATOR desiers to join them and to serve with their business and WTT Technology Service India Private Limited agrees to engage him/her as part their investment.'
		htvalue+='WHEREAS the ASSOCIATOR agrees that his/her association with the name WTT Technology Services India Private Limited and exposure to their exclusive intellectual properties will cause immense enrichment of his professional standing and consequently enhancement of his earning capacity. Hence, agrees that this agreement is of commercial value to him as well as to WTT Technology Services India Private Limited so he commits and undertakes to serve their business interest by the way of technical contributions or otherwise for a specified period to enable them to recover their investment on him/her or compensate them by way of penalty in the event of non-fulfillment of his obligations under this agreement.<br>The ASSOCIATOR shall be with WTT Technology Services India Private Limited Group firms and companies for a period of ____________ from the date of this agreement to the effect that he will develop his technical skills initially and consequently enrich his knowledge towards the productivity enhancement over a period of time.'
		htvalue+='<br><br><br>With best regards<br><br><b>SIVAKUMAR.P<br>General Manager - Admin<br>WTT Technology Services India Pvt Ltd</b><br><br>'
		htvalue+='<br><br>I accept the above Offer and shall join duties on _____________'
		htvalue+='<br><br>I accept all the terms and conditions and shall abide by the service rules of the Company.'
		htvalue+='<br><br>I hereby declare that I am accepting to work with the assigned designation willfully and later on, I will not claim for departmental change whatsoever based on my qualification.'
		htvalue+='<br><br><br><br>Signature ______________<br>Dated ______________'


	frm.set_value('html_text',htvalue);
	}
	else if(frm.doc.order_type=="Others"){
		var htvalue='Dear <b>Mr. '+frm.doc.employee_name+'</b><br><br>'
		htvalue+='We are pleased to offer you an appointment as <b>'+frm.doc.designation+'</b> with effect from <b>'+frm.doc.date+'</b>.You will be posted at Head Office Tirupur. You need to be stationed in the place of respective Head office and discharge your duties, on the following terms and conditions:'
		htvalue+='<br><br><b><u>Remuneration:</u></b><br><br>You will be paid a salary of <b>Rs. '+frm.doc.annual_salary+' /- per Annum (CTC) ('+frm.doc.in_words+')</b>. Salary structure enclosed (Annexure-I), you will not be entitled to any other allowances whatsoever. '
		htvalue+='<br><br><b><u>Probation:</u></b><br><br>You will be on probation for a period of three months from the date of Joining. The period may be extended at the sole discretion of the management.'
		htvalue+='<br><br><b><u>Transferability:</u></b><br><br>You are liable to be transferred / deputed to any other section / department or site of the company, or to any of the group / sister companies, that may be existing or acquired in future anywhere in territory of India at management’s sole discretion.'
		htvalue+='<br><br><b><u>Restrictions on outside business activities:</u></b><br><br>During your Training, You shall devote your full time, energy and ability exclusively to the causes of business interest of WTT Technology Services India Pvt Ltd and shall not Without our prior written consent, render to other service of any kind free or for compensation, or engage in any other business activity that would materially interfere with the performance of your obligation under this agreement.  You have to further represent that, you have no other outstanding commitments inconsistent with any of the terms of this Agreement.'
		htvalue+='<br><br><b><u>Covenant not to compete:</u></b><br><br>During your period of Association and 12 months after expiry of the period, you shall not, directly or indirectly, whether as partner, employee, creditor, shareholders or otherwise, promote, participate or engage in any activity or other business competitive/inimical to business interest of WTT Technology Services India Pvt Ltd.'
		htvalue+='<br><br><b><u>Non-disclosure obligations:</u></b><br><br>At all times during and after your association, You will hold in strictest confidence and not use for your own purpose or the purposes of others or disclose any thing even resembling on the Intellectual Properties belonging to WTT Technology Services India Pvt Ltd. to any person,  firm or corporation.  You will not publish or submit for publication any technical or other articles pertaining in any way to WTT Technology Services India Pvt Ltd. Intellectual Properties without our authorization in writing.'
		htvalue+='<br><br><b><u>Intellectual property:</u></b><br><br>The term Intellectual Property as it is used in this Agreement, shall include but not be limited to the following; <br><br>'
		htvalue+='a) Business or financial records, strategies, forecasts, budgets, Projections License, prices, costs, lists of current and prospective customers. Vendors Resume of Applicants of all category, training materials etc.<br>'
		htvalue+='b) Manufacturing techniques plans, processes formulas developments, experiments work-in-process, trade secrets ideas processes formulas training materials source codes, data, programs, inventions, confidential information, data, designs, drawings, consents, including but not limited to agnatic storage media compute memories or any electronic storage media which relates to the actual or prospective products, sales or businesses of WTT Technology Services India Pvt Ltd and which is not readily available to the public.  That know-how or any other information (Collective “inventions”) in whatever form, that term shall also include any information belonging to third parties in WTT Technology Services India Pvt Ltd’s possession and any information conceived, originated, discovered or developed by yourself in the course of your association with the company.'
		htvalue+='<br><br><b><u>Idle period:</u></b><br><br>You have to agree that you shall not claim any remuneration for the days your services were not availed by WTT Technology Services India Pvt Ltd.'
		htvalue+='<br><br><b><u>Termination on normal grounds:</u></b><br><br>WTT Technology Services India Pvt. Ltd. reserves the right to terminate the association/service on the normal grounds other than that of the in disciplinary actions with a prior notice of 3 months remuneration in lieu of notice.'
		htvalue+='<br><br><b><u>Return of WTT INDIA’s property:</u></b><br><br>You agree and undertake to return to WTT Technology Services India Pvt. Ltd all our files, drawings, blueprint, notebooks, memoranda, correspondence specifications, devices,  documents training materials & manuals, list of clients, diskettes and any material that embodies our Intellectual Properties of Confidential Information.  You further undertake that you shall not recreate any of the foregone.  You further agree that only a relieving order signed by the Authorized Signatory of WTT Technology Services India Pvt. Ltd. will confirm that you have surrendered all our material in your possession.'
		htvalue+='<br><br><b><u>Communication Address:</u></b><br><br>Your address indicated above shall be deemed to be correct address for sending you any communication and unless changed by the written intimation, the communication sent to you at the above address shall be deemed to have been correctly served.'
		htvalue+='<br><br><b><u>Rules and Regulations:</u></b><br><br>In all other matters not specifically mentioned herein, you will abide by the service/Standing Orders as applicable, enforced, amended or altered from time to time during the course of your employment.'
		htvalue+='<br><br><b><u>Complementary:</u></b><br><br>You shall not accept any presents, commissions, or any kind of gratification in Cash or kind from any person, party, firm or company having dealings with WTT Technology Services India Pvt Ltd and if you are offered you will report the same immediately to WTT Technology Services India Pvt. Ltd.'
		htvalue+='<br><br><b><u>Termination:</u></b><br><br>This appointment is liable for termination at any time by giving three months notice on either side in writing.<br><br>'
		htvalue+='This appointment order constitutes a valid and binding contract of service for the company and yourself.<br><br>'
		htvalue+='If the above terms and conditions are acceptable, you are requested to sign and deliver the duplicate copy of this order as a token of your acceptance.'
		htvalue+='<br><br><br>With best regards<br><br><b>SIVAKUMAR.P<br>General Manager - Admin<br>WTT Technology Services India Pvt Ltd</b><br><br>'
		htvalue+='<br><br>I accept the above Offer and shall join duties on _____________'
		htvalue+='<br><br>I accept all the terms and conditions and shall abide by the service rules of the Company.'
		htvalue+='<br><br>I hereby declare that I am accepting to work with the assigned designation willfully and later on, I will not claim for departmental change whatsoever based on my qualification.'
		htvalue+='<br><br><br><br>Signature ______________<br>Dated ______________'

	frm.set_value('html_text',htvalue);
	}
	else if(frm.doc.order_type==""){
		frm.set_value('html_text',"")
	}
}
});
});
	},
	template:function(frm){
		erpnext.utils.get_terms(frm.doc.template, frm.doc, function (r) {
			if (!r.exc) {
				frm.set_value("text_editor", r.message);
			}
		});
	},
	employee:function(frm){
		frappe.db.get_value('Employee', frm.doc.employee, ['applicant_address','address1','address2'], function(r) {
		    frm.set_value("address_line1", r.applicant_address);frm.refresh_field("address_line1");
		    frm.set_value("address_line2", r.address1);frm.refresh_field("address_line2");
		    frm.set_value("address_line3", r.address2);frm.refresh_field("address_line3");
		});
	},
	permanent:function(frm){
		if(frm.doc.permanent==1){
			frappe.db.get_value('Employee', frm.doc.employee, ['applicant_address2','address_1','address_2'], function(r) {
			    frm.set_value("address_line1", r.applicant_address2);frm.refresh_field("address_line1");
			    frm.set_value("address_line2", r.address_1);frm.refresh_field("address_line2");
			    frm.set_value("address_line3", r.address_2);frm.refresh_field("address_line3");
			});
		}
		else{
			frappe.db.get_value('Employee', frm.doc.employee, ['applicant_address','address1','address2'], function(r) {
			    frm.set_value("address_line1", r.applicant_address);frm.refresh_field("address_line1");
			    frm.set_value("address_line2", r.address1);frm.refresh_field("address_line2");
			    frm.set_value("address_line3", r.address2);frm.refresh_field("address_line3");
			});
		}
		

	}
});