name: Auto Upload

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure Git
        run: |
          git config --global user.email 'it@wttindia.com'
          git config --global user.name 'Your Name'
          git config --global credential.helper store
          echo "https://it@wttindia.com:${{ secrets.GITHUB_TOKEN }}" > ~/.git-credentials

      - name: Commit changes
        run: |
          cd ~/erpnext14/apps/wtt_module
          git add .
          git commit -m "Automated commit - $(date)"

      - name: Push changes
        run: |
          cd ~/erpnext14/apps/wtt_module
          git push origin master

